CREATE TABLE IF NOT EXISTS pay_merchant_pool (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    pool_name VARCHAR(128) NOT NULL,
    pool_code VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    remark VARCHAR(512) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pay_merchant_account (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    pool_id BIGINT NOT NULL,
    account_name VARCHAR(128) NOT NULL,
    channel_code VARCHAR(64) NOT NULL,
    api_key_encrypted TEXT NULL,
    sign_key_encrypted TEXT NULL,
    support_pay_methods VARCHAR(255) NOT NULL DEFAULT 'BARCODE_PAY',
    priority INT NOT NULL DEFAULT 100,
    weight INT NOT NULL DEFAULT 1,
    daily_amount_limit DECIMAL(18,2) NULL,
    monthly_amount_limit DECIMAL(18,2) NULL,
    single_min_amount DECIMAL(18,2) NULL,
    single_max_amount DECIMAL(18,2) NULL,
    available_start_date DATE NULL,
    available_end_date DATE NULL,
    available_start_time TIME NULL,
    available_end_time TIME NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    fail_count INT NOT NULL DEFAULT 0,
    last_fail_time DATETIME NULL,
    remark VARCHAR(512) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_pay_merchant_account_pool (pool_id),
    KEY idx_pay_merchant_account_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pay_merchant_account_secret (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    account_id BIGINT NOT NULL UNIQUE,
    api_key_encrypted TEXT NULL,
    private_key_encrypted TEXT NULL,
    public_key_encrypted TEXT NULL,
    cert_path VARCHAR(512) NULL,
    cert_password_encrypted TEXT NULL,
    extra_config_json TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pay_merchant_app (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    pool_id BIGINT NOT NULL,
    app_id VARCHAR(64) NOT NULL UNIQUE,
    app_name VARCHAR(128) NOT NULL,
    secret_encrypted TEXT NULL,
    notify_url_whitelist TEXT NULL,
    rate_limit_per_minute INT NOT NULL DEFAULT 60,
    status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
    remark VARCHAR(512) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_pay_merchant_app_pool (pool_id),
    KEY idx_pay_merchant_app_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO sys_permission (permission_code, permission_name) VALUES
('merchant:pool:view', 'View merchant pools'),
('merchant:pool:manage', 'Manage merchant pools'),
('merchant:account:view', 'View merchant accounts'),
('merchant:account:manage', 'Manage merchant accounts'),
('merchant:app:view', 'View merchant apps'),
('merchant:app:manage', 'Manage merchant apps');

INSERT IGNORE INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id FROM sys_role r JOIN sys_permission p
WHERE r.role_code = 'SUPER_ADMIN'
  AND p.permission_code IN ('merchant:pool:view', 'merchant:pool:manage', 'merchant:account:view', 'merchant:account:manage', 'merchant:app:view', 'merchant:app:manage');

INSERT IGNORE INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id FROM sys_role r JOIN sys_permission p
WHERE r.role_code = 'OPERATOR'
  AND p.permission_code IN ('merchant:pool:view', 'merchant:pool:manage', 'merchant:account:view', 'merchant:account:manage', 'merchant:app:view', 'merchant:app:manage');

INSERT IGNORE INTO sys_role_permission (role_id, permission_id)
SELECT r.id, p.id FROM sys_role r JOIN sys_permission p
WHERE r.role_code = 'AUDITOR'
  AND p.permission_code IN ('merchant:pool:view', 'merchant:account:view', 'merchant:app:view');

-- Merchant access app secrets are generated by the Spring schema initializer so
-- appSecret never reuses payment-channel signKey values.
