upstream payment_router_frontend {
    server frontend:80;
}

upstream payment_router_backend {
    server backend:8080;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 20m;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location = /api/doc.html {
        proxy_pass http://payment_router_backend/doc.html;
    }

    location /api/webjars/ {
        rewrite ^/api/webjars/(.*)$ /webjars/$1 break;
        proxy_pass http://payment_router_backend;
    }

    location /api/v3/api-docs/ {
        rewrite ^/api/v3/api-docs/(.*)$ /v3/api-docs/$1 break;
        proxy_pass http://payment_router_backend;
    }

    location = /api/v3/api-docs {
        proxy_pass http://payment_router_backend/v3/api-docs;
    }

    location /api/swagger-ui/ {
        rewrite ^/api/swagger-ui/(.*)$ /swagger-ui/$1 break;
        proxy_pass http://payment_router_backend;
    }

    location /api/ {
        proxy_pass http://payment_router_backend/api/;
    }

    location /admin/ {
        proxy_pass http://payment_router_backend/admin/;
    }

    location /actuator/ {
        proxy_pass http://payment_router_backend/actuator/;
    }

    location = /doc.html {
        proxy_pass http://payment_router_backend/doc.html;
    }

    location /webjars/ {
        proxy_pass http://payment_router_backend/webjars/;
    }

    location /v3/api-docs/ {
        proxy_pass http://payment_router_backend/v3/api-docs/;
    }

    location = /v3/api-docs {
        proxy_pass http://payment_router_backend/v3/api-docs;
    }

    location /swagger-ui/ {
        proxy_pass http://payment_router_backend/swagger-ui/;
    }

    location / {
        proxy_pass http://payment_router_frontend;
    }
}
